# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def BuildNextjsProjectComponent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.NextJSComponentGeneratorOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="BuildNextjsProjectComponent", llm_response=llm_response, mode="request")
        return typing.cast(types.NextJSComponentGeneratorOutput, result)

    def CritiqueNextjsProjectStructure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="CritiqueNextjsProjectStructure", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def GetFramework(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Framework:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GetFramework", llm_response=llm_response, mode="request")
        return typing.cast(types.Framework, result)

    def NodeRouteGenerator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.NodeJSRouteGeneratorOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="NodeRouteGenerator", llm_response=llm_response, mode="request")
        return typing.cast(types.NodeJSRouteGeneratorOutput, result)

    def PlanExpressServer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.NodeProjectStructure:
        result = self.__options.merge_options(baml_options).parse_response(function_name="PlanExpressServer", llm_response=llm_response, mode="request")
        return typing.cast(types.NodeProjectStructure, result)

    def PlanNextjsProjectGenerationSteps(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.NextjsProjectStructure:
        result = self.__options.merge_options(baml_options).parse_response(function_name="PlanNextjsProjectGenerationSteps", llm_response=llm_response, mode="request")
        return typing.cast(types.NextjsProjectStructure, result)

    def PreprocessUserPrompt(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="PreprocessUserPrompt", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def PromptBreakdownForNextGeneration(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="PromptBreakdownForNextGeneration", llm_response=llm_response, mode="request")
        return typing.cast(typing.List[str], result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def BuildNextjsProjectComponent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.NextJSComponentGeneratorOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="BuildNextjsProjectComponent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.NextJSComponentGeneratorOutput, result)

    def CritiqueNextjsProjectStructure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="CritiqueNextjsProjectStructure", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def GetFramework(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Framework:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GetFramework", llm_response=llm_response, mode="stream")
        return typing.cast(types.Framework, result)

    def NodeRouteGenerator(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.NodeJSRouteGeneratorOutput:
        result = self.__options.merge_options(baml_options).parse_response(function_name="NodeRouteGenerator", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.NodeJSRouteGeneratorOutput, result)

    def PlanExpressServer(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.NodeProjectStructure:
        result = self.__options.merge_options(baml_options).parse_response(function_name="PlanExpressServer", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.NodeProjectStructure, result)

    def PlanNextjsProjectGenerationSteps(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.NextjsProjectStructure:
        result = self.__options.merge_options(baml_options).parse_response(function_name="PlanNextjsProjectGenerationSteps", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.NextjsProjectStructure, result)

    def PreprocessUserPrompt(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="PreprocessUserPrompt", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def PromptBreakdownForNextGeneration(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[str]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="PromptBreakdownForNextGeneration", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List[str], result)

    