# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def BuildNextjsProjectComponent(self, component: types.NextJSProjectComponent,
        baml_options: BamlCallOptions = {},
    ) -> types.NextJSComponentGeneratorOutput:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.BuildNextjsProjectComponent(component=component,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="BuildNextjsProjectComponent", args={
                "component": component,
            })
            return typing.cast(types.NextJSComponentGeneratorOutput, result.cast_to(types, types, stream_types, False, __runtime__))
    def CritiqueNextjsProjectStructure(self, structure: types.NextjsProjectStructure,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.CritiqueNextjsProjectStructure(structure=structure,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="CritiqueNextjsProjectStructure", args={
                "structure": structure,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def GetFramework(self, prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Framework:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.GetFramework(prompt=prompt,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="GetFramework", args={
                "prompt": prompt,
            })
            return typing.cast(types.Framework, result.cast_to(types, types, stream_types, False, __runtime__))
    def NodeRouteGenerator(self, generated_prompt: types.NodeJSProjectComponent,
        baml_options: BamlCallOptions = {},
    ) -> types.NodeJSRouteGeneratorOutput:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.NodeRouteGenerator(generated_prompt=generated_prompt,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="NodeRouteGenerator", args={
                "generated_prompt": generated_prompt,
            })
            return typing.cast(types.NodeJSRouteGeneratorOutput, result.cast_to(types, types, stream_types, False, __runtime__))
    def PlanExpressServer(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.NodeProjectStructure:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.PlanExpressServer(user_prompt=user_prompt,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="PlanExpressServer", args={
                "user_prompt": user_prompt,
            })
            return typing.cast(types.NodeProjectStructure, result.cast_to(types, types, stream_types, False, __runtime__))
    def PlanNextjsProjectGenerationSteps(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.NextjsProjectStructure:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.PlanNextjsProjectGenerationSteps(user_prompt=user_prompt,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="PlanNextjsProjectGenerationSteps", args={
                "user_prompt": user_prompt,
            })
            return typing.cast(types.NextjsProjectStructure, result.cast_to(types, types, stream_types, False, __runtime__))
    def PreprocessUserPrompt(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.PreprocessUserPrompt(user_prompt=user_prompt,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="PreprocessUserPrompt", args={
                "user_prompt": user_prompt,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def BuildNextjsProjectComponent(self, component: types.NextJSProjectComponent,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.NextJSComponentGeneratorOutput, types.NextJSComponentGeneratorOutput]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="BuildNextjsProjectComponent", args={
            "component": component,
        })
        return baml_py.BamlSyncStream[stream_types.NextJSComponentGeneratorOutput, types.NextJSComponentGeneratorOutput](
          result,
          lambda x: typing.cast(stream_types.NextJSComponentGeneratorOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.NextJSComponentGeneratorOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def CritiqueNextjsProjectStructure(self, structure: types.NextjsProjectStructure,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="CritiqueNextjsProjectStructure", args={
            "structure": structure,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GetFramework(self, prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[types.Framework, types.Framework]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GetFramework", args={
            "prompt": prompt,
        })
        return baml_py.BamlSyncStream[types.Framework, types.Framework](
          result,
          lambda x: typing.cast(types.Framework, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Framework, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def NodeRouteGenerator(self, generated_prompt: types.NodeJSProjectComponent,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.NodeJSRouteGeneratorOutput, types.NodeJSRouteGeneratorOutput]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="NodeRouteGenerator", args={
            "generated_prompt": generated_prompt,
        })
        return baml_py.BamlSyncStream[stream_types.NodeJSRouteGeneratorOutput, types.NodeJSRouteGeneratorOutput](
          result,
          lambda x: typing.cast(stream_types.NodeJSRouteGeneratorOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.NodeJSRouteGeneratorOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def PlanExpressServer(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.NodeProjectStructure, types.NodeProjectStructure]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="PlanExpressServer", args={
            "user_prompt": user_prompt,
        })
        return baml_py.BamlSyncStream[stream_types.NodeProjectStructure, types.NodeProjectStructure](
          result,
          lambda x: typing.cast(stream_types.NodeProjectStructure, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.NodeProjectStructure, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def PlanNextjsProjectGenerationSteps(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.NextjsProjectStructure, types.NextjsProjectStructure]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="PlanNextjsProjectGenerationSteps", args={
            "user_prompt": user_prompt,
        })
        return baml_py.BamlSyncStream[stream_types.NextjsProjectStructure, types.NextjsProjectStructure](
          result,
          lambda x: typing.cast(stream_types.NextjsProjectStructure, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.NextjsProjectStructure, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def PreprocessUserPrompt(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="PreprocessUserPrompt", args={
            "user_prompt": user_prompt,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def BuildNextjsProjectComponent(self, component: types.NextJSProjectComponent,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="BuildNextjsProjectComponent", args={
            "component": component,
        }, mode="request")
        return result
    def CritiqueNextjsProjectStructure(self, structure: types.NextjsProjectStructure,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="CritiqueNextjsProjectStructure", args={
            "structure": structure,
        }, mode="request")
        return result
    def GetFramework(self, prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetFramework", args={
            "prompt": prompt,
        }, mode="request")
        return result
    def NodeRouteGenerator(self, generated_prompt: types.NodeJSProjectComponent,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="NodeRouteGenerator", args={
            "generated_prompt": generated_prompt,
        }, mode="request")
        return result
    def PlanExpressServer(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PlanExpressServer", args={
            "user_prompt": user_prompt,
        }, mode="request")
        return result
    def PlanNextjsProjectGenerationSteps(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PlanNextjsProjectGenerationSteps", args={
            "user_prompt": user_prompt,
        }, mode="request")
        return result
    def PreprocessUserPrompt(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PreprocessUserPrompt", args={
            "user_prompt": user_prompt,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def BuildNextjsProjectComponent(self, component: types.NextJSProjectComponent,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="BuildNextjsProjectComponent", args={
            "component": component,
        }, mode="stream")
        return result
    def CritiqueNextjsProjectStructure(self, structure: types.NextjsProjectStructure,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="CritiqueNextjsProjectStructure", args={
            "structure": structure,
        }, mode="stream")
        return result
    def GetFramework(self, prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GetFramework", args={
            "prompt": prompt,
        }, mode="stream")
        return result
    def NodeRouteGenerator(self, generated_prompt: types.NodeJSProjectComponent,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="NodeRouteGenerator", args={
            "generated_prompt": generated_prompt,
        }, mode="stream")
        return result
    def PlanExpressServer(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PlanExpressServer", args={
            "user_prompt": user_prompt,
        }, mode="stream")
        return result
    def PlanNextjsProjectGenerationSteps(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PlanNextjsProjectGenerationSteps", args={
            "user_prompt": user_prompt,
        }, mode="stream")
        return result
    def PreprocessUserPrompt(self, user_prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PreprocessUserPrompt", args={
            "user_prompt": user_prompt,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))