# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.NextJSProjectComponent": types.NextJSProjectComponent,
    "stream_types.NextJSProjectComponent": stream_types.NextJSProjectComponent,

    "types.NodeJSProjectComponent": types.NodeJSProjectComponent,
    "stream_types.NodeJSProjectComponent": stream_types.NodeJSProjectComponent,

    "types.NodeJSRouteGeneratorOutput": types.NodeJSRouteGeneratorOutput,
    "stream_types.NodeJSRouteGeneratorOutput": stream_types.NodeJSRouteGeneratorOutput,

    "types.ProjectStructure": types.ProjectStructure,
    "stream_types.ProjectStructure": stream_types.ProjectStructure,


    "types.AnalyticsProvider": types.AnalyticsProvider,

    "types.CommandType": types.CommandType,

    "types.ComponentType": types.ComponentType,

    "types.DesignSystem": types.DesignSystem,

    "types.Framework": types.Framework,

    "types.TestType": types.TestType,

}