import type { FileNode } from "@/zustand";

export const dummyFileTree: FileNode[] = [
  {
    name: "app",
    path: "/app",
    type: "folder",
    children: [
      {
        name: "layout.tsx",
        path: "/app/layout.tsx",
        type: "file",
        content: `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'My Next.js App',
  description: 'Generated by Bolt.newer',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`,
      },
      {
        name: "page.tsx",
        path: "/app/page.tsx",
        type: "file",
        content: `export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-4xl font-bold mb-4">
        Welcome to My Next.js App
      </h1>
      <p className="text-lg text-gray-600">
        This is a dummy project generated by Bolt.newer
      </p>
    </main>
  )
}`,
      },
      {
        name: "globals.css",
        path: "/app/globals.css",
        type: "file",
        content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}`,
      },
      {
        name: "components",
        path: "/app/components",
        type: "folder",
        children: [
          {
            name: "Button.tsx",
            path: "/app/components/Button.tsx",
            type: "file",
            content: `'use client'

interface ButtonProps {
  children: React.ReactNode
  onClick?: () => void
  variant?: 'primary' | 'secondary'
}

export default function Button({
  children,
  onClick,
  variant = 'primary',
}: ButtonProps) {
  return (
    <button
      onClick={onClick}
      className={\`px-4 py-2 rounded \${
        variant === 'primary'
          ? 'bg-blue-500 text-white'
          : 'bg-gray-200 text-gray-800'
      }\`}
    >
      {children}
    </button>
  )
}`,
          },
          {
            name: "Card.tsx",
            path: "/app/components/Card.tsx",
            type: "file",
            content: `interface CardProps {
  children: React.ReactNode
  title?: string
}

export default function Card({ children, title }: CardProps) {
  return (
    <div className="border rounded-lg p-4 shadow-sm">
      {title && (
        <h2 className="text-xl font-semibold mb-2">{title}</h2>
      )}
      {children}
    </div>
  )
}`,
          },
        ],
      },
    ],
  },
  {
    name: "public",
    path: "/public",
    type: "folder",
    children: [
      {
        name: "favicon.ico",
        path: "/public/favicon.ico",
        type: "file",
        content: "// Binary file - favicon.ico",
      },
    ],
  },
  {
    name: "package.json",
    path: "/package.json",
    type: "file",
    content: `{
  "name": "my-nextjs-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.0.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}`,
  },
  {
    name: "tsconfig.json",
    path: "/tsconfig.json",
    type: "file",
    content: `{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`,
  },
  {
    name: "tailwind.config.js",
    path: "/tailwind.config.js",
    type: "file",
    content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`,
  },
  {
    name: "next.config.js",
    path: "/next.config.js",
    type: "file",
    content: `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig`,
  },
  {
    name: ".gitignore",
    path: "/.gitignore",
    type: "file",
    content: `# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts`,
  },
  {
    name: "README.md",
    path: "/README.md",
    type: "file",
    content: `# My Next.js App

This is a Next.js application generated by Bolt.newer.

## Getting Started

First, run the development server:

\`\`\`bash
npm run dev
# or
yarn dev
# or
pnpm dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Learn More

To learn more about Next.js, take a look at the following resources:

- [Next.js Documentation](https://nextjs.org/docs) - learn about Next.js features and API.
- [Learn Next.js](https://nextjs.org/learn) - an interactive Next.js tutorial.`,
  },
];

// Helper function to extract all file contents from the tree
export function extractFileContents(tree: FileNode[]): Record<string, string> {
  const contents: Record<string, string> = {};

  function traverse(nodes: FileNode[]) {
    for (const node of nodes) {
      if (node.type === "file" && node.content) {
        contents[node.path] = node.content;
      } else if (node.type === "folder" && node.children) {
        traverse(node.children);
      }
    }
  }

  traverse(tree);
  return contents;
}

