import Card from "../ui/Card";

export default function CodeViewer() {
  return (
    <Card variant="inset" className="h-full">
      <div className="h-full flex flex-col">
        <div className="neo-flat neo-rounded-sm p-2 mb-2">
          <span className="text-sm text-[var(--text-secondary)] font-mono">
            /app/page.tsx
          </span>
        </div>
        <div className="flex-1 overflow-auto">
          <pre className="text-sm text-[var(--text-secondary)] font-mono p-4 whitespace-pre-wrap">
            <code>{`export default function Home() {
  return (
    <main className="min-h-screen p-8">
      <h1 className="text-4xl font-bold mb-4">
        Welcome to My Next.js App
      </h1>
      <p className="text-lg text-gray-600">
        This is a dummy project generated by Bolt.newer
      </p>
    </main>
  )
}`}</code>
          </pre>
        </div>
      </div>
    </Card>
  );
}
